/**
 * @terminus/model-router — Deep Model Profiles.
 *
 * Per SPEC §26: Deep profiles specialize instructions, context ordering, tool
 * schemas, edit formats, reasoning effort, continuation, compaction, caching,
 * and known error mitigations without provider lock-in.
 */
import type { ModelProfile } from "@terminus/domain";

export const CLAUDE_3_7_SONNET_PROFILE: ModelProfile = {
  id: "profile-anthropic-claude-3-7-sonnet-20250219-v1",
  providerId: "anthropic",
  modelKey: "claude-3-7-sonnet-20250219",
  version: "2025-02-19-v1",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 200_000,
    testedSafeTokens: 160_000,
    supportsImages: true,
  },
  toolDialect: "anthropic_tools",
  editDialect: "hash_anchored_diff",
  reasoningEffortPolicy: "high",
  continuationStrategy: "native_token",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "explicit_breakpoints",
    minTokens: 1024,
    exactPrefixRequired: true,
  },
  structuredOutputRepair: {
    dialect: "prompt_guided_json",
    autoRepair: true,
    retryPromptTemplate: "Format error in tool parameters. Output valid JSON matching the exact schema definition.",
  },
  knownFailureMitigations: [
    "strip_markdown_json_fences",
    "deduplicate_parallel_tool_calls",
    "normalize_relative_file_paths",
  ],
  economics: {
    inputMicrosPerMillion: 3_000_000n,
    cachedInputMicrosPerMillion: 300_000n,
    outputMicrosPerMillion: 15_000_000n,
    reasoningAccounting: true,
  },
  latencyModel: {
    p50Ms: 850,
    p90Ms: 1800,
    p99Ms: 3500,
    ttftMs: 350,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 200_000,
    securityReasoning: "high",
  },
};

export const CLAUDE_3_5_HAIKU_PROFILE: ModelProfile = {
  id: "profile-anthropic-claude-3-5-haiku-20241022-v1",
  providerId: "anthropic",
  modelKey: "claude-3-5-haiku-20241022",
  version: "2024-10-22-v1",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 200_000,
    testedSafeTokens: 128_000,
    supportsImages: true,
  },
  toolDialect: "anthropic_tools",
  editDialect: "hash_anchored_diff",
  reasoningEffortPolicy: "none",
  continuationStrategy: "native_token",
  compactionStrategy: "rolling_summary",
  cachingStrategy: {
    mode: "explicit_breakpoints",
    minTokens: 2048,
    exactPrefixRequired: true,
  },
  structuredOutputRepair: {
    dialect: "prompt_guided_json",
    autoRepair: true,
    retryPromptTemplate: "Return strictly valid JSON according to schema.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences"],
  economics: {
    inputMicrosPerMillion: 800_000n,
    cachedInputMicrosPerMillion: 80_000n,
    outputMicrosPerMillion: 4_000_000n,
    reasoningAccounting: false,
  },
  latencyModel: {
    p50Ms: 250,
    p90Ms: 600,
    p99Ms: 1200,
    ttftMs: 150,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent"],
  capabilities: {
    codingQuality: "medium",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 200_000,
    securityReasoning: "medium",
  },
};

export const GPT_4O_PROFILE: ModelProfile = {
  id: "profile-openai-gpt-4o-2024-11-20-v1",
  providerId: "openai",
  modelKey: "gpt-4o-2024-11-20",
  version: "2024-11-20-v1",
  contextLayout: {
    systemPromptPlacement: "developer_message",
    maxContextTokens: 128_000,
    testedSafeTokens: 100_000,
    supportsImages: true,
  },
  toolDialect: "openai_function_calling",
  editDialect: "search_replace_blocks",
  reasoningEffortPolicy: "none",
  continuationStrategy: "server_history",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "automatic_prefix",
    minTokens: 1024,
    exactPrefixRequired: true,
  },
  structuredOutputRepair: {
    dialect: "strict_json_schema",
    autoRepair: true,
    retryPromptTemplate: "Fix invalid JSON parameters for function call.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences", "normalize_newline_escapes"],
  economics: {
    inputMicrosPerMillion: 2_500_000n,
    cachedInputMicrosPerMillion: 1_250_000n,
    outputMicrosPerMillion: 10_000_000n,
    reasoningAccounting: false,
  },
  latencyModel: {
    p50Ms: 650,
    p90Ms: 1400,
    p99Ms: 2800,
    ttftMs: 280,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 128_000,
    securityReasoning: "high",
  },
};

export const O3_MINI_PROFILE: ModelProfile = {
  id: "profile-openai-o3-mini-2025-01-31-v1",
  providerId: "openai",
  modelKey: "o3-mini-2025-01-31",
  version: "2025-01-31-v1",
  contextLayout: {
    systemPromptPlacement: "developer_message",
    maxContextTokens: 200_000,
    testedSafeTokens: 160_000,
    supportsImages: false,
  },
  toolDialect: "openai_function_calling",
  editDialect: "hash_anchored_diff",
  reasoningEffortPolicy: "high",
  continuationStrategy: "server_history",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "automatic_prefix",
    minTokens: 1024,
    exactPrefixRequired: true,
  },
  structuredOutputRepair: {
    dialect: "strict_json_schema",
    autoRepair: true,
    retryPromptTemplate: "Reasoning model structured error. Fix function argument JSON.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences"],
  economics: {
    inputMicrosPerMillion: 1_100_000n,
    cachedInputMicrosPerMillion: 550_000n,
    outputMicrosPerMillion: 4_400_000n,
    reasoningAccounting: true,
  },
  latencyModel: {
    p50Ms: 1200,
    p90Ms: 3200,
    p99Ms: 6000,
    ttftMs: 900,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 200_000,
    securityReasoning: "high",
  },
};

export const GEMINI_2_0_FLASH_PROFILE: ModelProfile = {
  id: "profile-google-gemini-2-0-flash-001-v1",
  providerId: "google",
  modelKey: "gemini-2.0-flash-001",
  version: "001-v1",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 1_048_576,
    testedSafeTokens: 500_000,
    supportsImages: true,
  },
  toolDialect: "gemini_function_declarations",
  editDialect: "search_replace_blocks",
  reasoningEffortPolicy: "none",
  continuationStrategy: "client_replay",
  compactionStrategy: "rolling_summary",
  cachingStrategy: {
    mode: "explicit_resource",
    minTokens: 32_768,
    exactPrefixRequired: true,
  },
  structuredOutputRepair: {
    dialect: "strict_json_schema",
    autoRepair: true,
    retryPromptTemplate: "Format Gemini function arguments strictly as JSON schema.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences", "sanitize_gemini_thought_blocks"],
  economics: {
    inputMicrosPerMillion: 100_000n,
    cachedInputMicrosPerMillion: 25_000n,
    outputMicrosPerMillion: 400_000n,
    reasoningAccounting: false,
  },
  latencyModel: {
    p50Ms: 220,
    p90Ms: 500,
    p99Ms: 1100,
    ttftMs: 140,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 1_048_576,
    securityReasoning: "medium",
  },
};

export const GEMINI_1_5_PRO_PROFILE: ModelProfile = {
  id: "profile-google-gemini-1-5-pro-002-v1",
  providerId: "google",
  modelKey: "gemini-1.5-pro-002",
  version: "002-v1",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 2_097_152,
    testedSafeTokens: 1_000_000,
    supportsImages: true,
  },
  toolDialect: "gemini_function_declarations",
  editDialect: "search_replace_blocks",
  reasoningEffortPolicy: "medium",
  continuationStrategy: "client_replay",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "explicit_resource",
    minTokens: 32_768,
    exactPrefixRequired: true,
  },
  structuredOutputRepair: {
    dialect: "strict_json_schema",
    autoRepair: true,
    retryPromptTemplate: "Format Gemini function arguments strictly as JSON schema.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences"],
  economics: {
    inputMicrosPerMillion: 1_250_000n,
    cachedInputMicrosPerMillion: 312_500n,
    outputMicrosPerMillion: 5_000_000n,
    reasoningAccounting: false,
  },
  latencyModel: {
    p50Ms: 950,
    p90Ms: 2200,
    p99Ms: 4500,
    ttftMs: 400,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 2_097_152,
    securityReasoning: "high",
  },
};

export const LOCAL_LLAMA_3_3_70B_PROFILE: ModelProfile = {
  id: "profile-local-llama-3-3-70b-instruct-v1",
  providerId: "local",
  modelKey: "llama-3.3-70b-instruct",
  version: "v1-local",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 128_000,
    testedSafeTokens: 64_000,
    supportsImages: false,
  },
  toolDialect: "standard_json_schema",
  editDialect: "hash_anchored_diff",
  reasoningEffortPolicy: "none",
  continuationStrategy: "client_replay",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "none",
    minTokens: 0,
    exactPrefixRequired: false,
  },
  structuredOutputRepair: {
    dialect: "grammar_constrained",
    autoRepair: true,
    retryPromptTemplate: "Output strictly JSON according to the schema without preamble.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences", "repair_unclosed_json"],
  economics: {
    inputMicrosPerMillion: 0n,
    cachedInputMicrosPerMillion: 0n,
    outputMicrosPerMillion: 0n,
    reasoningAccounting: false,
  },
  latencyModel: {
    p50Ms: 700,
    p90Ms: 1500,
    p99Ms: 3000,
    ttftMs: 200,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent", "secret"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "medium",
    structuredOutput: true,
    contextTokens: 128_000,
    securityReasoning: "medium",
  },
};

export const LOCAL_QWEN_2_5_CODER_32B_PROFILE: ModelProfile = {
  id: "profile-local-qwen-2-5-coder-32b-v1",
  providerId: "local",
  modelKey: "qwen-2.5-coder-32b",
  version: "v1-local",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 128_000,
    testedSafeTokens: 64_000,
    supportsImages: false,
  },
  toolDialect: "standard_json_schema",
  editDialect: "hash_anchored_diff",
  reasoningEffortPolicy: "none",
  continuationStrategy: "client_replay",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "none",
    minTokens: 0,
    exactPrefixRequired: false,
  },
  structuredOutputRepair: {
    dialect: "grammar_constrained",
    autoRepair: true,
    retryPromptTemplate: "Format code patch strictly according to tool specification.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences"],
  economics: {
    inputMicrosPerMillion: 0n,
    cachedInputMicrosPerMillion: 0n,
    outputMicrosPerMillion: 0n,
    reasoningAccounting: false,
  },
  latencyModel: {
    p50Ms: 400,
    p90Ms: 900,
    p99Ms: 1800,
    ttftMs: 120,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent", "secret"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "high",
    structuredOutput: true,
    contextTokens: 128_000,
    securityReasoning: "medium",
  },
};

export const LOCAL_DEEPSEEK_R1_DISTILL_32B_PROFILE: ModelProfile = {
  id: "profile-local-deepseek-r1-distill-qwen-32b-v1",
  providerId: "local",
  modelKey: "deepseek-r1-distill-qwen-32b",
  version: "v1-local",
  contextLayout: {
    systemPromptPlacement: "system_message",
    maxContextTokens: 64_000,
    testedSafeTokens: 32_000,
    supportsImages: false,
  },
  toolDialect: "standard_json_schema",
  editDialect: "hash_anchored_diff",
  reasoningEffortPolicy: "high",
  continuationStrategy: "client_replay",
  compactionStrategy: "structured_claims_with_evidence",
  cachingStrategy: {
    mode: "none",
    minTokens: 0,
    exactPrefixRequired: false,
  },
  structuredOutputRepair: {
    dialect: "grammar_constrained",
    autoRepair: true,
    retryPromptTemplate: "Reasoning completed. Provide exact JSON tool call payload.",
  },
  knownFailureMitigations: ["strip_markdown_json_fences", "strip_deepseek_think_tags"],
  economics: {
    inputMicrosPerMillion: 0n,
    cachedInputMicrosPerMillion: 0n,
    outputMicrosPerMillion: 0n,
    reasoningAccounting: true,
  },
  latencyModel: {
    p50Ms: 1100,
    p90Ms: 2500,
    p99Ms: 5000,
    ttftMs: 800,
  },
  confidentialityPolicy: ["public", "workspace", "secret_adjacent", "secret"],
  capabilities: {
    codingQuality: "high",
    toolReliability: "medium",
    structuredOutput: true,
    contextTokens: 64_000,
    securityReasoning: "high",
  },
};

export const STANDARD_MODEL_PROFILES: readonly ModelProfile[] = [
  CLAUDE_3_7_SONNET_PROFILE,
  CLAUDE_3_5_HAIKU_PROFILE,
  GPT_4O_PROFILE,
  O3_MINI_PROFILE,
  GEMINI_2_0_FLASH_PROFILE,
  GEMINI_1_5_PRO_PROFILE,
  LOCAL_LLAMA_3_3_70B_PROFILE,
  LOCAL_QWEN_2_5_CODER_32B_PROFILE,
  LOCAL_DEEPSEEK_R1_DISTILL_32B_PROFILE,
];
