#!/usr/bin/env bun
/**
 * codegen-docs — run every doc-generating codegen step and emit an index.
 *
 * SPEC §45.3 lists `codegen-docs` as the aggregator that produces the
 * ADR index, event catalog markdown, API docs, etc. This script invokes
 * the four doc-emitting generators and then writes `docs/generated/INDEX.md`
 * listing every generated file plus its source-of-truth file.
 *
 * Drift detection is handled by `just codegen-check`, which runs `just
 * codegen` and then `git diff --exit-code` against the generated trees.
 */
import { spawnSync } from "node:child_process";
import { writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.FORGE_ROOT ?? join(import.meta.dir, "..", "..");
const OUT_DIR = join(ROOT, "docs", "generated");

const GENERATORS: Array<{ name: string; script: string; source: string }> = [
  { name: "Event catalog", script: "tools/codegen/events.ts", source: "schemas/events/catalog.yaml" },
  { name: "Tool schema catalog", script: "tools/codegen/tools.ts", source: "schemas/tools/*.json" },
  { name: "Configuration reference", script: "tools/codegen/config.ts", source: "packages/config/src/index.ts" },
  { name: "Public API surface", script: "tools/codegen/public-api.ts", source: "packages/public-api/src/index.ts" },
  { name: "SQLx deviation note", script: "tools/codegen/sqlx.ts", source: "migrations/sqlite/" },
];

function run(script: string): boolean {
  const r = spawnSync("bun", ["run", script], { cwd: ROOT, stdio: "inherit" });
  return r.status === 0;
}

function main(): void {
  let allOk = true;
  for (const g of GENERATORS) {
    console.log(`[codegen-docs] running ${g.name} (${g.script})`);
    if (!run(g.script)) {
      console.error(`[codegen-docs] ${g.name} failed`);
      allOk = false;
    }
  }

  // Emit the index.
  mkdirSync(OUT_DIR, { recursive: true });
  const generated = readdirSync(OUT_DIR)
    .filter((f) => f.endsWith(".md") && f !== "INDEX.md")
    .sort();
  const lines: string[] = [];
  lines.push("# Generated documentation index");
  lines.push("");
  lines.push("> Auto-generated by `tools/codegen/docs.ts`. Do not edit by hand.");
  lines.push("> Every file in this directory is derived from a source-of-truth file");
  lines.push("> elsewhere in the repo. Run `just codegen` to regenerate; `just codegen-check`");
  lines.push("> verifies there is no drift (SPEC §45.2).");
  lines.push("");
  lines.push("## Generators");
  lines.push("");
  lines.push("| Generator | Source of truth | Output |");
  lines.push("|---|---|---|");
  for (const g of GENERATORS) {
    const out = g.script.replace(/^tools\/codegen\/(.+)\.ts$/, "$1.md");
    lines.push(`| ${g.name} | \`${g.source}\` | \`${out}\` |`);
  }
  lines.push("");
  lines.push("## Generated files");
  lines.push("");
  if (generated.length === 0) {
    lines.push("_No generated files found. Run `just codegen`._");
  } else {
    lines.push("| File | Size |");
    lines.push("|---|---:|");
    for (const f of generated) {
      const size = statSync(join(OUT_DIR, f)).size;
      lines.push(`| \`${f}\` | ${size} B |`);
    }
  }
  lines.push("");
  writeFileSync(join(OUT_DIR, "INDEX.md"), lines.join("\n") + "\n", "utf8");
  console.log(`[codegen-docs] wrote ${join(OUT_DIR, "INDEX.md")} (${generated.length} generated files)`);

  if (!allOk) process.exit(1);
}

main();
