#!/usr/bin/env bun
/**
 * codegen-public-api — verify the public-API surface of Terminus packages.
 *
 * SPEC §45.3 mandates a `codegen-public-api` generator that emits
 * OpenAPI clients from `packages/public-api`. Generating real OpenAPI
 * requires running the Next.js app or a separate spec file. Until the
 * OpenAPI document is checked in, this script:
 *
 *  1. Type-checks the public-api package via `tsc --noEmit` against the
 *     packages tsconfig (fast, no emit).
 *  2. Emits a small Markdown table summarising the exports declared by
 *     `packages/public-api/src/index.ts` so downstream tooling and
 *     reviewers can see the public surface.
 *
 * When a real OpenAPI document is added, replace step 2 with an
 * `openapi-typescript-codegen` invocation.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = process.env.FORGE_ROOT ?? join(import.meta.dir, "..", "..");
const SRC = join(ROOT, "packages", "public-api", "src", "index.ts");
const OUT_DIR = join(ROOT, "docs", "generated");
const OUT = join(OUT_DIR, "public-api.md");

function parseExports(src: string): { name: string; kind: string }[] {
  const out: { name: string; kind: string }[] = [];
  // Match: `export const X`, `export function X`, `export class X`,
  // `export interface X`, `export type X`, `export enum X`,
  // `export { X, Y }` (best-effort).
  const patterns: Array<[string, RegExp]> = [
    ["const", /\bexport\s+const\s+([A-Za-z_$][A-Za-z0-9_$]*)/g],
    ["function", /\bexport\s+function\s+([A-Za-z_$][A-Za-z0-9_$]*)/g],
    ["class", /\bexport\s+class\s+([A-Za-z_$][A-Za-z0-9_$]*)/g],
    ["interface", /\bexport\s+interface\s+([A-Za-z_$][A-Za-z0-9_$]*)/g],
    ["type", /\bexport\s+type\s+([A-Za-z_$][A-Za-z0-9_$]*)/g],
    ["enum", /\bexport\s+enum\s+([A-Za-z_$][A-Za-z0-9_$]*)/g],
  ];
  for (const [kind, re] of patterns) {
    let m: RegExpExecArray | null;
    while ((m = re.exec(src)) !== null) {
      out.push({ name: m[1]!, kind });
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

function main(): void {
  // Step 1: type-check the packages workspace. If tsc is not available or
  // the project hasn't been bootstrapped, emit a warning but don't fail —
  // `bun run typecheck:packages` is already invoked by `just check`.
  const tsc = spawnSync("bunx", ["tsc", "--noEmit", "-p", "tsconfig.packages.json"], {
    cwd: ROOT,
    encoding: "utf8",
  });
  if (tsc.status !== 0) {
    console.warn("[codegen-public-api] tsc --noEmit returned non-zero; emitting catalog only");
    if (tsc.stdout) console.warn(tsc.stdout);
    if (tsc.stderr) console.warn(tsc.stderr);
  } else {
    console.log("[codegen-public-api] tsc --noEmit (packages) OK");
  }

  // Step 2: emit the public-surface catalog.
  if (!existsSync(SRC)) {
    console.error(`[codegen-public-api] ${SRC} does not exist; nothing to catalog`);
    process.exit(1);
  }
  const src = readFileSync(SRC, "utf8");
  const exports = parseExports(src);
  const lines: string[] = [];
  lines.push("# Terminus Public API Surface");
  lines.push("");
  lines.push("> Auto-generated by `tools/codegen/public-api.ts`. Do not edit by hand.");
  lines.push("> Source of truth: `packages/public-api/src/index.ts`.");
  lines.push("> When an OpenAPI document is added, this catalog should be replaced by");
  lines.push("> generated OpenAPI clients (SPEC §45.3).");
  lines.push("");
  lines.push(`Total exports: **${exports.length}**`);
  lines.push("");
  if (exports.length === 0) {
    lines.push("_No exports declared._");
  } else {
    lines.push("| Export | Kind |");
    lines.push("|---|---|");
    for (const e of exports) lines.push(`| \`${e.name}\` | ${e.kind} |`);
  }
  lines.push("");
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
  console.log(`[codegen-public-api] wrote ${OUT} (${exports.length} exports)`);
}

main();
