#!/usr/bin/env bun
/**
 * codegen-sqlx — document the Terminus persistence deviation from SPEC §45.3.
 *
 * SPEC §45.3 lists a `codegen-sqlx` command that emits SQLx offline query
 * metadata from `migrations/sqlite/`. Terminus deliberately uses Prisma +
 * a checked-in SQL migration file (`migrations/sqlite/0001_initial.sql`)
 * instead of runtime SQLx queries — see ADR-0005 ("Hybrid SQLite +
 * events/artifact persistence") and the per-ADR note in `docs/decisions/`.
 *
 * This script:
 *  1. Verifies the SQL migrations directory is non-empty (the SQLx
 *     data-source for any future Rust SQLx adopter lives there).
 *  2. Emits a short Markdown stub at `docs/generated/sqlx.md` recording
 *     the deviation so `codegen-check` still detects drift.
 */
import { readdirSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.FORGE_ROOT ?? join(import.meta.dir, "..", "..");
const MIGRATIONS_DIR = join(ROOT, "migrations", "sqlite");
const OUT_DIR = join(ROOT, "docs", "generated");
const OUT = join(OUT_DIR, "sqlx.md");

function main(): void {
  if (!existsSync(MIGRATIONS_DIR)) {
    console.error(`[codegen-sqlx] migrations directory missing: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }
  const sql = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  if (sql.length === 0) {
    console.error("[codegen-sqlx] no *.sql files in migrations/sqlite/ — refusing to emit");
    process.exit(1);
  }
  const lines: string[] = [];
  lines.push("# Terminus SQLx codegen — deviation note");
  lines.push("");
  lines.push("> Auto-generated by `tools/codegen/sqlx.ts`. Do not edit by hand.");
  lines.push("");
  lines.push("Terminus does **not** use SQLx at runtime. ADR-0005 records the decision to");
  lines.push("use a hybrid SQLite + events/artifact persistence layer driven by Prisma");
  lines.push("on the control-plane side and a checked-in SQL migration file on the");
  lines.push("kernel side. The `codegen-sqlx` recipe is retained for SPEC §45.3");
  lines.push("compatibility and emits this note so `codegen-check` can detect drift.");
  lines.push("");
  lines.push("## Available SQL migrations");
  lines.push("");
  lines.push("| File |");
  lines.push("|---|");
  for (const f of sql) lines.push(`| \`${f}\` |`);
  lines.push("");
  lines.push("If a future Rust crate adopts SQLx, replace this script with");
  lines.push("`cargo sqlx prepare --workspace --check` and emit the resulting");
  lines.push("`.sqlx/` directory as the codegen artifact.");
  lines.push("");
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");
  console.log(`[codegen-sqlx] wrote ${OUT} (deviation documented; ${sql.length} SQL files)`);
}

main();
