#!/usr/bin/env bun
/**
 * codegen-tools — emit a Markdown catalog from schemas/tools/*.json.
 *
 * SPEC §45.6 mandates a generator that derives provider dialects,
 * validators, and a Markdown catalog from the tool schemas. This script
 * emits the Markdown catalog under docs/generated/tools.md. Provider
 * dialect generation is a future addition (tracked separately).
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.FORGE_ROOT ?? join(import.meta.dir, "..", "..");
const SRC_DIR = join(ROOT, "schemas", "tools");
const OUT_DIR = join(ROOT, "docs", "generated");
const OUT = join(OUT_DIR, "tools.md");

interface ToolProp {
  name: string;
  type: string;
  description: string;
  required: boolean;
}
interface ToolSchema {
  id: string;
  title: string;
  description: string;
  required: string[];
  props: ToolProp[];
}

function typeStr(def: unknown): string {
  if (typeof def !== "object" || def === null) return "any";
  const d = def as Record<string, unknown>;
  if (Array.isArray(d["type"])) {
    return (d["type"] as string[]).filter((t) => t !== "null").join(" | ") + " | null";
  }
  if (typeof d["type"] === "string") return d["type"];
  if (d["enum"]) return "enum: " + (d["enum"] as unknown[]).map((v) => JSON.stringify(v)).join(" | ");
  if (d["$ref"]) return String(d["$ref"]);
  if (d["additionalProperties"]) return "object";
  return "object";
}

function loadTool(file: string): ToolSchema {
  const raw = JSON.parse(readFileSync(join(SRC_DIR, file), "utf8")) as Record<string, unknown>;
  const title = String(raw["title"] ?? file);
  const description = String(raw["description"] ?? "");
  const required = (raw["required"] as string[] | undefined) ?? [];
  const propsNode = (raw["properties"] as Record<string, unknown> | undefined) ?? {};
  const props: ToolProp[] = Object.entries(propsNode).map(([name, def]) => {
    const d = (def ?? {}) as Record<string, unknown>;
    return {
      name,
      type: typeStr(def),
      description: typeof d["description"] === "string" ? d["description"] : "",
      required: required.includes(name),
    };
  });
  return {
    id: String(raw["$id"] ?? `https://forge.dev/schemas/tools/${file}`),
    title,
    description,
    required,
    props,
  };
}

function render(tools: ToolSchema[]): string {
  const lines: string[] = [];
  lines.push("# Forge Tool Schema Catalog");
  lines.push("");
  lines.push("> Auto-generated by `tools/codegen/tools.ts`. Do not edit by hand.");
  lines.push("> Source of truth: `schemas/tools/*.json` (SPEC §45.6).");
  lines.push("");
  lines.push(`Total tools: **${tools.length}**`);
  lines.push("");
  lines.push("| Tool | Required params | Optional params |");
  lines.push("|---|---|---|");
  for (const t of tools) {
    const req = t.props.filter((p) => p.required).map((p) => `\`${p.name}\``).join(", ") || "—";
    const opt = t.props.filter((p) => !p.required).map((p) => `\`${p.name}\``).join(", ") || "—";
    lines.push(`| \`${t.title}\` | ${req} | ${opt} |`);
  }
  lines.push("");
  lines.push("## Parameter reference");
  lines.push("");
  for (const t of tools) {
    lines.push(`### \`${t.title}\``);
    lines.push("");
    lines.push(`- **Schema:** ${t.id}`);
    lines.push(`- **Description:** ${t.description}`);
    lines.push("");
    if (t.props.length === 0) {
      lines.push("_No parameters._");
      lines.push("");
      continue;
    }
    lines.push("| Parameter | Type | Required | Description |");
    lines.push("|---|---|---|---|");
    for (const p of t.props) {
      const desc = p.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
      lines.push(`| \`${p.name}\` | ${p.type} | ${p.required ? "yes" : "no"} | ${desc} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

function main(): void {
  const files = readdirSync(SRC_DIR).filter((f) => f.endsWith(".json")).sort();
  if (files.length === 0) {
    console.error("[codegen-tools] no tool schemas found in schemas/tools/");
    process.exit(1);
  }
  const tools = files.map(loadTool);
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, render(tools) + "\n", "utf8");
  console.log(`[codegen-tools] wrote ${OUT} (${tools.length} tools)`);
}

main();
